sonar.organization=soulsilver-awsd
sonar.projectKey=Soulsilver-awsd_front-pokedex

sonar.projectName=front-podekex
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/assets/**,**/environments/**
